version: '3.2'
services:
  db:
    image: 'postgres:13'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - "8080:8080"